const STORAGE_KEY='pdr-oabt-2014-exam-v2';
const state={data:null,current:0,answers:{},bookmarks:{},startedAt:null,deadline:null,finished:false,reviewIndex:null,reviewTab:'explanation'};
const $=s=>document.querySelector(s);
const els={welcome:$('#welcomeView'),exam:$('#examView'),results:$('#resultsView'),topic:$('#topic'),number:$('#questionNumber'),question:$('#questionText'),visual:$('#questionVisual'),options:$('#options'),prev:$('#prevButton'),next:$('#nextButton'),bookmark:$('#bookmark'),grid:$('#questionGrid'),bar:$('#progressBar'),progressLabel:$('#progressLabel'),answeredLabel:$('#answeredLabel'),timer:$('#timer'),optic:$('#opticPanel'),finishHint:$('#finishHint'),modal:$('#finishModal'),toast:$('#toast')};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({current:state.current,answers:state.answers,bookmarks:state.bookmarks,startedAt:state.startedAt,deadline:state.deadline,finished:state.finished}))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(STORAGE_KEY))||{})}catch(_){}}
function q(){return state.data.questions[state.current]}
function show(view){els.welcome.hidden=view!=='welcome';els.exam.hidden=view!=='exam';els.results.hidden=view!=='results';window.scrollTo(0,0)}
function toast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),1900)}
function begin(fresh=false){if(fresh){state.current=0;state.answers={};state.bookmarks={};state.finished=false;state.startedAt=Date.now();state.deadline=state.startedAt+75*60*1000}else if(!state.startedAt){state.startedAt=Date.now();state.deadline=state.startedAt+75*60*1000}show('exam');renderQuestion();save()}
function renderQuestion(){const item=q();els.topic.textContent=item.topic;els.number.textContent=String(item.number).padStart(2,'0');els.question.textContent=item.question;els.visual.hidden=!item.hasOriginalVisual;if(item.hasOriginalVisual)els.visual.src=item.visual;els.bookmark.setAttribute('aria-pressed',!!state.bookmarks[item.id]);els.bookmark.textContent=state.bookmarks[item.id]?'♥ İşaretlendi':'♡ Sonra bak';els.options.innerHTML='';item.options.forEach(opt=>{const b=document.createElement('button');b.type='button';b.className='option'+(state.answers[item.id]===opt.key?' selected':'');b.setAttribute('role','radio');b.setAttribute('aria-checked',state.answers[item.id]===opt.key);b.innerHTML=`<span class="option-key">${opt.key}</span><span>${opt.text}</span>`;b.onclick=()=>{state.answers[item.id]=opt.key;renderQuestion()};els.options.appendChild(b)});els.prev.disabled=state.current===0;els.next.textContent=state.current===state.data.questionCount-1?'Optik forma dön →':'Sonraki soru →';renderProgress();renderGrid();save()}
function renderProgress(){const count=Object.keys(state.answers).length,remaining=state.data.questionCount-count;els.progressLabel.textContent=`Soru ${state.current+1} / ${state.data.questionCount}`;els.answeredLabel.textContent=`${count} yanıtlandı`;els.bar.style.width=`${count/state.data.questionCount*100}%`;els.finishHint.textContent=remaining?`${remaining} soru kaldı`:'Tümü yanıtlandı'}
function renderGrid(){els.grid.innerHTML='';state.data.questions.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.className='grid-button';b.textContent=item.number;if(state.answers[item.id])b.classList.add('answered');if(state.bookmarks[item.id])b.classList.add('flagged');if(i===state.current)b.classList.add('current');b.onclick=()=>{state.current=i;renderQuestion();els.optic.classList.remove('open')};els.grid.appendChild(b)})}
function tryFinish(){const remaining=state.data.questionCount-Object.keys(state.answers).length;if(remaining){toast(`Sınavı bitirmek için ${remaining} soruyu daha yanıtlamalısın.`);return}els.modal.hidden=false}
function finish(){state.finished=true;save();els.modal.hidden=true;renderResults();show('results')}
function resultStats(){let correct=0,wrong=0,blank=0;state.data.questions.forEach(item=>{const a=state.answers[item.id];if(!a)blank++;else if(a===item.answer)correct++;else wrong++});return{correct,wrong,blank}}
function renderResults(){const s=resultStats(),percent=Math.round(s.correct/state.data.questionCount*100);$('#correctCount').textContent=s.correct;$('#wrongCount').textContent=s.wrong;$('#blankCount').textContent=s.blank;$('#scorePercent').textContent=percent;$('#scoreTitle').textContent=percent>=80?'Çok güçlü bir sonuç!':percent>=60?'İyi gidiyorsun.':'Gelişim alanların hazır.';const grid=$('#resultGrid');grid.innerHTML='';state.data.questions.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.className='result-button '+(!state.answers[item.id]?'blank':state.answers[item.id]===item.answer?'correct':'wrong');b.textContent=item.number;b.title=`${item.number}. soruyu incele`;b.onclick=()=>openReview(i,b);grid.appendChild(b)})}
function openReview(index,button){state.reviewIndex=index;state.reviewTab='explanation';document.querySelectorAll('.result-button').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelectorAll('[data-review-tab]').forEach((b,i)=>b.classList.toggle('active',i===0));$('#reviewEmpty').hidden=true;$('#reviewContent').hidden=false;renderReview()}
function renderReview(){const item=state.data.questions[state.reviewIndex],user=state.answers[item.id]||'Boş';$('#reviewTopic').textContent=item.topic;$('#reviewNumber').textContent=`${item.number}. soru`;$('#reviewQuestion').textContent=item.question;$('#answerComparison').innerHTML=`Senin cevabın: <b>${user}</b> &nbsp;·&nbsp; Doğru cevap: <b>${item.answer}</b>`;$('#reviewText').textContent=item[state.reviewTab]||''}
els.prev.onclick=()=>{if(state.current>0){state.current--;renderQuestion()}};els.next.onclick=()=>{if(state.current<state.data.questionCount-1){state.current++;renderQuestion()}else els.optic.classList.add('open')};els.bookmark.onclick=()=>{const id=q().id;state.bookmarks[id]=!state.bookmarks[id];renderQuestion()};$('#startExam').onclick=()=>begin(true);$('#resumeExam').onclick=()=>begin(false);$('#homeButton').onclick=e=>{e.preventDefault();show('welcome')};$('#openOptic').onclick=()=>els.optic.classList.add('open');$('#closeOptic').onclick=()=>els.optic.classList.remove('open');$('#finishExam').onclick=tryFinish;$('#cancelFinish').onclick=()=>els.modal.hidden=true;$('#confirmFinish').onclick=finish;$('#restartExam').onclick=()=>{if(confirm('Mevcut sonuçların silinip sınav yeniden başlatılsın mı?'))begin(true)};document.querySelectorAll('[data-review-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-review-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.reviewTab=b.dataset.reviewTab;renderReview()});
setInterval(()=>{if(!state.startedAt||state.finished)return;const left=Math.max(0,state.deadline-Date.now()),m=String(Math.floor(left/60000)).padStart(2,'0'),s=String(Math.floor(left%60000/1000)).padStart(2,'0');els.timer.textContent=`${m}:${s}`;if(left===0){state.finished=true;save();renderResults();show('results')}},1000);
fetch('data/2014.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{state.data=data;load();const hasProgress=Object.keys(state.answers).length>0&&!state.finished;$('#resumeExam').hidden=!hasProgress;if(state.finished){renderResults();show('results')}else show('welcome')}).catch(()=>{$('.welcome-copy h1').textContent='Soru verileri yüklenemedi.'});
